### ISSUE TITLE
Missing register values in custom PAGE object cause TYPO3.CMS.Frontend.ContentObject.Exception

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#50]
Just a note after debugging and fixing this in a project:

- using t3sbootstrap 4.4.8 on TYPO3 9.5.20
- we use luxletter
- this has custom PAGE objects fluidStyledMailContent, luxletterPreviewNewsletter ...
- you have to set `fluidStyledMailContent.1 < page.1` and `luxletterPreviewNewsletter.1 < page.1`
- otherwise you get a TYPO3.CMS.Frontend.ContentObject.Exception with "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in /typo3_src-9.5.20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:"

Maybe you could add a hint in the documentation (and try prevent empty value in ConfigProcessor)

stacktrace:
```
[ALERT] request="558d046fd882c" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 20200828170414a9523258 - {"exception":"Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in /typo3_src-9.5.20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:86\nStack trace:\
n#0 /typo3_src-9.5.20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php(131): Doctrine\\DBAL\\Driver\\Mysqli\\MysqliStatement->__construct(Object(mysqli), 'SELECT * FROM `...')\
n#1 /typo3_src-9.5.20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php(141): Doctrine\\DBAL\\Driver\\Mysqli\\MysqliConnection->prepare('SELECT * FROM `...')\
n#2 /typo3_src-9.5.20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(909): Doctrine\\DBAL\\Driver\\Mysqli\\MysqliConnection->query('SELECT * FROM `...')\
n#3 /typo3_src-9.5.20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): Doctrine\\DBAL\\Connection->executeQuery('SELECT * FROM `...', Array, Array)\
n#4 /typo3_src-9.5.20/typo3/sysext/core/Classes/Database/Query/QueryBuilder.php(191): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\
n#5 /cms/typo3conf/ext/t3sbootstrap/Classes/Helper/DefaultHelper.php(107): TYPO3\\CMS\\Core\\Database\\Query\\QueryBuilder->execute()\
n#6 /cms/typo3conf/ext/t3sbootstrap/Classes/Helper/DefaultHelper.php(42): T3SBS\\T3sbootstrap\\Helper\\DefaultHelper->getConfig('')\
n#7 /cms/typo3conf/ext/t3sbootstrap/Classes/DataProcessing/BootstrapProcessor.php(419): T3SBS\\T3sbootstrap\\Helper\\DefaultHelper->getContainerClass(Array)\
n#8 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/ContentDataProcessor.php(63): T3SBS\\T3sbootstrap\\DataProcessing\\BootstrapProcessor->process(Object(TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer), Array, Array, Array)\n#9 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/FluidTemplateContentObject.php(102): TYPO3\\CMS\\Frontend\\ContentObject\\ContentDataProcessor->process(Object(TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer), Array, Array)\
n#10 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(815): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render(Array)\
n#11 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(731): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject), Array)\
n#12 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(713): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'lib.contentElem...')\
n#13 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/CaseContentObject.php(46): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'textmedia')\
n#14 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(815): TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject->render(Array)\
n#15 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(731): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject), Array)\
n#16 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(713): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CASE', Array, 'tt_content')\
n#17 /typo3_src-9.5.20/typo3/sysext/frontend/Classes/ContentObject/ContentContentObject.php(94): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CASE', Array, '')\


```

**Comment by t3solution** [comment]
New version 5 - new issues!
